INFO     cardano_node_tests.tests.test_pools:test_pools.py:88 Waiting up to 3 epochs for stake pool to be registered.
ERROR    cardano_node_tests.utils.clusterlib:clusterlib.py:261 An error occurred running a CLI command `cardano-cli shelley query stake-distribution --testnet-magic 42 --shelley-mode`: 
cardano-cli: Network.Socket.connect: <socket: 11>: resource exhausted (Resource temporarily unavailable)